/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.domij.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.domij.parser.antlr.internal.InternalDomijmasdslParser;
import org.xtext.example.domij.services.DomijmasdslGrammarAccess;

public class DomijmasdslParser extends AbstractAntlrParser {

	@Inject
	private DomijmasdslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDomijmasdslParser createParser(XtextTokenStream stream) {
		return new InternalDomijmasdslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}

	public DomijmasdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DomijmasdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
