/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.domij.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.domijmasdsl.ui.internal.DomijmasdslActivator;

public class DomijmasdslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DomijmasdslActivator.getInstance().getInjector("org.xtext.example.domij.Domijmasdsl");
	}

}
