/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.domij.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomijmasdslScopeProvider extends DelegatingScopeProvider {
}
