/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.domij;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DomijmasdslStandaloneSetup extends DomijmasdslStandaloneSetupGenerated {

	public static void doSetup() {
		new DomijmasdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
