/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.domij.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.domij.DomijmasdslRuntimeModule;
import org.xtext.example.domij.DomijmasdslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DomijmasdslIdeSetup extends DomijmasdslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DomijmasdslRuntimeModule(), new DomijmasdslIdeModule()));
	}
	
}
