/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.domij.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DomijmasdslUiModule extends AbstractDomijmasdslUiModule {

	public DomijmasdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
