/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.domij.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.domijmasdsl.ui.internal.DomijmasdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomijmasdslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DomijmasdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DomijmasdslActivator activator = DomijmasdslActivator.getInstance();
		return activator != null ? activator.getInjector(DomijmasdslActivator.ORG_XTEXT_EXAMPLE_DOMIJ_DOMIJMASDSL) : null;
	}

}
